[tools]
go = "1.12"
node = "13"
yarn = "1"

[tasks.up]
run = "docker-compose up -d --build"
dir = "docker"
description = "Run Stratus in a docker container without the need to install dependencies on local machine"

[tasks.down]
run = "docker-compose down"
dir = "docker"
description = "Teardown Stratus docker container"
