services:
  client:
    container_name: stratus-client
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
      - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
      - REACT_APP_FIREBASE_SENDER_ID=${REACT_APP_FIREBASE_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
      - REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}
    command: bash -c "serve -s client"
    depends_on:
      - server
    networks:
      - stratus-network

  server:
    container_name: stratus-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /app/server
    ports:
      - '8080:8080'
    command: bash -c "./stratus-server"
    networks:
      - stratus-network
    volumes:
      - './projects:/app/server/output'

networks:
  stratus-network:
